-- MySQL Script generated by MySQL Workbench
-- Wed Sep 17 22:01:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @@SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema supermercato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supermercato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supermercato` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `supermercato`;

-- -----------------------------------------------------
-- Table `supermercato`.`edifici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`edifici` (
    `id_edificio` INT NOT NULL AUTO_INCREMENT,
    `nome_edificio` VARCHAR(100) NOT NULL,
    `indirizzo` VARCHAR(255) NULL DEFAULT NULL,
    `superficie_mq` INT NULL DEFAULT NULL,
    `funzione_principale` ENUM(
        'Punto Vendita',
        'Magazzino',
        'Sede'
    ) NOT NULL,
    PRIMARY KEY (`id_edificio`)
) ENGINE = InnoDB AUTO_INCREMENT = 4 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`casse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`casse` (
    `id_cassa` INT NOT NULL AUTO_INCREMENT,
    `numero_cassa` INT NOT NULL,
    `tipo` ENUM('Manuale', 'Automatica') NOT NULL,
    `stato` ENUM(
        'Attiva',
        'In manutenzione',
        'Disattivata'
    ) NULL DEFAULT 'Attiva',
    `id_edificio` INT NOT NULL,
    PRIMARY KEY (`id_cassa`),
    INDEX `id_edificio` (`id_edificio` ASC) VISIBLE,
    CONSTRAINT `casse_ibfk_1` FOREIGN KEY (`id_edificio`) REFERENCES `supermercato`.`edifici` (`id_edificio`)
) ENGINE = InnoDB AUTO_INCREMENT = 23 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`fornitori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`fornitori` (
    `id_fornitore` INT NOT NULL AUTO_INCREMENT,
    `nome_fornitore` VARCHAR(100) NOT NULL,
    `partita_iva` VARCHAR(20) NOT NULL,
    `email` VARCHAR(150) NULL DEFAULT NULL,
    `telefono` VARCHAR(20) NULL DEFAULT NULL,
    `affidabilita` TINYINT NULL DEFAULT NULL,
    PRIMARY KEY (`id_fornitore`),
    UNIQUE INDEX `partita_iva` (`partita_iva` ASC) VISIBLE
) ENGINE = InnoDB AUTO_INCREMENT = 151 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`produttori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`produttori` (
    `id_produttore` INT NOT NULL AUTO_INCREMENT,
    `nome_produttore` VARCHAR(100) NOT NULL,
    `nazione` VARCHAR(50) NULL DEFAULT NULL,
    `sito_web` VARCHAR(150) NULL DEFAULT NULL,
    `telefono` VARCHAR(20) NULL DEFAULT NULL,
    PRIMARY KEY (`id_produttore`)
) ENGINE = InnoDB AUTO_INCREMENT = 501 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`marche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`marche` (
    `id_marca` INT NOT NULL AUTO_INCREMENT,
    `nome_marca` VARCHAR(100) NOT NULL,
    `id_produttore` INT NOT NULL,
    PRIMARY KEY (`id_marca`),
    INDEX `id_produttore` (`id_produttore` ASC) VISIBLE,
    CONSTRAINT `marche_ibfk_1` FOREIGN KEY (`id_produttore`) REFERENCES `supermercato`.`produttori` (`id_produttore`)
) ENGINE = InnoDB AUTO_INCREMENT = 512 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`categorie` (
    `id_categoria` INT NOT NULL AUTO_INCREMENT,
    `nome_categoria` VARCHAR(100) NOT NULL,
    `descrizione` TEXT NULL DEFAULT NULL,
    PRIMARY KEY (`id_categoria`)
) ENGINE = InnoDB AUTO_INCREMENT = 110 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`sottocategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`sottocategorie` (
    `id_sottocategoria` INT NOT NULL AUTO_INCREMENT,
    `nome_sottocategoria` VARCHAR(100) NOT NULL,
    `id_categoria` INT NOT NULL,
    PRIMARY KEY (`id_sottocategoria`),
    INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
    CONSTRAINT `sottocategorie_ibfk_1` FOREIGN KEY (`id_categoria`) REFERENCES `supermercato`.`categorie` (`id_categoria`)
) ENGINE = InnoDB AUTO_INCREMENT = 437 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`prodotti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`prodotti` (
    `id_prodotto` INT NOT NULL AUTO_INCREMENT,
    `nome_prodotto` VARCHAR(150) NOT NULL,
    `prezzo_vendita` DECIMAL(10, 2) NOT NULL,
    `peso_kg` DECIMAL(6, 3) NULL DEFAULT NULL,
    `volume_cm3` INT NULL DEFAULT NULL,
    `id_marca` INT NOT NULL,
    `id_sottocategoria` INT NOT NULL,
    `is_alimentare` TINYINT(1) NULL DEFAULT '1',
    PRIMARY KEY (`id_prodotto`),
    INDEX `id_marca` (`id_marca` ASC) VISIBLE,
    INDEX `id_sottocategoria` (`id_sottocategoria` ASC) VISIBLE,
    CONSTRAINT `prodotti_ibfk_1` FOREIGN KEY (`id_marca`) REFERENCES `supermercato`.`marche` (`id_marca`),
    CONSTRAINT `prodotti_ibfk_2` FOREIGN KEY (`id_sottocategoria`) REFERENCES `supermercato`.`sottocategorie` (`id_sottocategoria`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`lotti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`lotti` (
    `id_lotto` INT NOT NULL AUTO_INCREMENT,
    `codice_lotto` VARCHAR(50) NOT NULL,
    `id_prodotto` INT NOT NULL,
    `data_produzione` DATE NULL,
    `data_scadenza` DATE NULL,
    PRIMARY KEY (`id_lotto`),
    INDEX `id_prodotto` (`id_prodotto` ASC) VISIBLE,
    CONSTRAINT `lotti_ibfk_1` FOREIGN KEY (`id_prodotto`) REFERENCES `supermercato`.`prodotti` (`id_prodotto`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`catalogo_fornitori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`catalogo_fornitori` (
    `id_fornitore` INT NOT NULL,
    `id_prodotto` INT NOT NULL,
    `prezzo_offerta` DECIMAL(10, 2) NOT NULL,
    `data_inizio` DATE NOT NULL,
    `data_fine` DATE NOT NULL,
    PRIMARY KEY (`id_fornitore`, `id_prodotto`),
    INDEX `id_prodotto` (`id_prodotto` ASC) VISIBLE,
    CONSTRAINT `catalogo_fornitori_ibfk_1` FOREIGN KEY (`id_fornitore`) REFERENCES `supermercato`.`fornitori` (`id_fornitore`),
    CONSTRAINT `catalogo_fornitori_ibfk_2` FOREIGN KEY (`id_prodotto`) REFERENCES `supermercato`.`prodotti` (`id_prodotto`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`clienti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`clienti` (
    `id_cliente` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(100) NOT NULL,
    `cognome` VARCHAR(100) NOT NULL,
    `data_nascita` DATE NOT NULL,
    `sesso` ENUM('M', 'F', 'Altro') NULL DEFAULT NULL,
    `lavoro` VARCHAR(150) NULL DEFAULT NULL,
    `email` VARCHAR(150) NULL DEFAULT NULL,
    `telefono` VARCHAR(20) NULL DEFAULT NULL,
    `residenza` VARCHAR(255) NULL DEFAULT NULL,
    `newsletter` TINYINT(1) NULL DEFAULT '0',
    PRIMARY KEY (`id_cliente`),
    UNIQUE INDEX `email` (`email` ASC) VISIBLE,
    UNIQUE INDEX `telefono` (`telefono` ASC) VISIBLE
) ENGINE = InnoDB AUTO_INCREMENT = 1001 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`titoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`titoli` (
    `id_titolo` INT NOT NULL AUTO_INCREMENT,
    `nome_titolo` VARCHAR(100) NOT NULL,
    `ente_emittente` VARCHAR(100) NULL DEFAULT NULL,
    `data_conseguimento` DATE NULL DEFAULT NULL,
    `data_scadenza` DATE NULL DEFAULT NULL,
    `eqf` INT NULL DEFAULT NULL,
    PRIMARY KEY (`id_titolo`)
) ENGINE = InnoDB AUTO_INCREMENT = 28 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`clienti_titoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`clienti_titoli` (
    `id_cliente` INT NOT NULL,
    `id_titolo` INT NOT NULL,
    PRIMARY KEY (`id_cliente`, `id_titolo`),
    INDEX `id_titolo` (`id_titolo` ASC) VISIBLE,
    CONSTRAINT `clienti_titoli_ibfk_1` FOREIGN KEY (`id_cliente`) REFERENCES `supermercato`.`clienti` (`id_cliente`),
    CONSTRAINT `clienti_titoli_ibfk_2` FOREIGN KEY (`id_titolo`) REFERENCES `supermercato`.`titoli` (`id_titolo`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`ordini_fornitore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`ordini_fornitore` (
    `id_ordine` INT NOT NULL AUTO_INCREMENT,
    `id_fornitore` INT NOT NULL,
    `data_ordine` DATE NOT NULL,
    `data_prevista_consegna` DATE NULL DEFAULT NULL,
    `stato` ENUM(
        'In attesa',
        'Consegnato',
        'Annullato'
    ) NULL DEFAULT 'In attesa',
    PRIMARY KEY (`id_ordine`),
    INDEX `id_fornitore` (`id_fornitore` ASC) VISIBLE,
    CONSTRAINT `ordini_fornitore_ibfk_1` FOREIGN KEY (`id_fornitore`) REFERENCES `supermercato`.`fornitori` (`id_fornitore`)
) ENGINE = InnoDB AUTO_INCREMENT = 85051 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`dettagli_ordine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`dettagli_ordine` (
    `id_dettaglio` INT NOT NULL AUTO_INCREMENT,
    `id_ordine` INT NOT NULL,
    `id_prodotto` INT NOT NULL,
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`dipendenti_titoli` (
    `id_dipendente` INT NOT NULL,
    `id_titolo` INT NOT NULL,
    PRIMARY KEY (`id_dipendente`, `id_titolo`),
    INDEX `id_titolo` (`id_titolo` ASC) VISIBLE,
    CONSTRAINT `dipendenti_titoli_ibfk_1` FOREIGN KEY (`id_dipendente`) REFERENCES `supermercato`.`dipendenti` (`id_dipendente`),
    CONSTRAINT `dipendenti_titoli_ibfk_2` FOREIGN KEY (`id_titolo`) REFERENCES `supermercato`.`titoli` (`id_titolo`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`reparti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`reparti` (
    `id_reparto` INT NOT NULL AUTO_INCREMENT,
    `nome_reparto` VARCHAR(100) NOT NULL,
    `descrizione` TEXT NULL DEFAULT NULL,
    PRIMARY KEY (`id_reparto`)
) ENGINE = InnoDB AUTO_INCREMENT = 17 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`scaffali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`scaffali` (
    `id_scaffale` INT NOT NULL AUTO_INCREMENT,
    `tipo` ENUM(
        'Normale',
        'Frigorifero',
        'Congelatore'
    ) NOT NULL,
    `capacita_peso` DECIMAL(10, 2) NOT NULL,
    `capacita_volume` DECIMAL(10, 2) NOT NULL,
    `id_reparto` INT NOT NULL,
    `id_edificio` INT NOT NULL,
    PRIMARY KEY (`id_scaffale`),
    INDEX `id_reparto` (`id_reparto` ASC) VISIBLE,
    INDEX `id_edificio` (`id_edificio` ASC) VISIBLE,
    CONSTRAINT `scaffali_ibfk_1` FOREIGN KEY (`id_reparto`) REFERENCES `supermercato`.`reparti` (`id_reparto`),
    CONSTRAINT `scaffali_ibfk_2` FOREIGN KEY (`id_edificio`) REFERENCES `supermercato`.`edifici` (`id_edificio`)
) ENGINE = InnoDB AUTO_INCREMENT = 60 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`giacenze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`giacenze` (
    `id_giacenza` INT NOT NULL AUTO_INCREMENT,
    `id_lotto` INT NOT NULL,
    `id_scaffale` INT NOT NULL,
    `quantita` INT NOT NULL,
    `data_collocazione` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id_giacenza`),
    INDEX `id_lotto` (`id_lotto` ASC) VISIBLE,
    INDEX `id_scaffale` (`id_scaffale` ASC) VISIBLE,
    CONSTRAINT `giacenze_ibfk_1` FOREIGN KEY (`id_lotto`) REFERENCES `supermercato`.`lotti` (`id_lotto`),
    CONSTRAINT `giacenze_ibfk_2` FOREIGN KEY (`id_scaffale`) REFERENCES `supermercato`.`scaffali` (`id_scaffale`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`promozioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`promozioni` (
    `id_promozione` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(100) NOT NULL,
    `descrizione` TEXT NULL DEFAULT NULL,
    `sconto_percentuale` DECIMAL(5, 2) NULL DEFAULT NULL,
    `data_inizio` DATE NOT NULL,
    `data_fine` DATE NOT NULL,
    PRIMARY KEY (`id_promozione`)
) ENGINE = InnoDB AUTO_INCREMENT = 13 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`promozioni_prodotti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`promozioni_prodotti` (
    `id_promozione` INT NOT NULL,
    `id_prodotto` INT NOT NULL,
    PRIMARY KEY (
        `id_promozione`,
        `id_prodotto`
    ),
    INDEX `id_prodotto` (`id_prodotto` ASC) VISIBLE,
    CONSTRAINT `promozioni_prodotti_ibfk_1` FOREIGN KEY (`id_promozione`) REFERENCES `supermercato`.`promozioni` (`id_promozione`),
    CONSTRAINT `promozioni_prodotti_ibfk_2` FOREIGN KEY (`id_prodotto`) REFERENCES `supermercato`.`prodotti` (`id_prodotto`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`reparto_edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`reparto_edificio` (
    `id_reparto` INT NOT NULL,
    `id_edificio` INT NOT NULL,
    PRIMARY KEY (`id_reparto`, `id_edificio`),
    INDEX `id_edificio` (`id_edificio` ASC) VISIBLE,
    CONSTRAINT `reparto_edificio_ibfk_1` FOREIGN KEY (`id_reparto`) REFERENCES `supermercato`.`reparti` (`id_reparto`),
    CONSTRAINT `reparto_edificio_ibfk_2` FOREIGN KEY (`id_edificio`) REFERENCES `supermercato`.`edifici` (`id_edificio`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `supermercato`.`ruoli_titoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`ruoli_titoli` (
    `id_ruolo` INT NOT NULL,
    `id_titolo` INT NOT NULL,
    PRIMARY KEY (`id_ruolo`, `id_titolo`),
    INDEX `id_titolo` (`id_titolo` ASC) VISIBLE,
    CONSTRAINT `ruoli_titoli_ibfk_1` FOREIGN KEY (`id_ruolo`) REFERENCES `supermercato`.`ruoli` (`id_ruolo`),
    CONSTRAINT `ruoli_titoli_ibfk_2` FOREIGN KEY (`id_titolo`) REFERENCES `supermercato`.`titoli` (`id_titolo`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

USE `supermercato`;

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_average_order_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_average_order_value` (`aov` INT);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_cannibalizzazione_promozioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_cannibalizzazione_promozioni` (
    `prodotto_promozione_1` INT,
    `prodotto_promozione_2` INT,
    `scontrini_comuni` INT,
    `qta_prodotto_1` INT,
    `qta_prodotto_2` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_carrello_medio_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_carrello_medio_cliente` (
    `id_cliente` INT,
    `nome` INT,
    `cognome` INT,
    `carrello_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_carrello_medio_tipologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_carrello_medio_tipologia` (
    `lavoro` INT,
    `carrello_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_clienti_registrati_vs_anonimi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_clienti_registrati_vs_anonimi` (
    `vendite_clienti_registrati` INT,
    `vendite_clienti_anonimi` INT,
    `totale_vendite` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_clienti_ritorno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_clienti_ritorno` (
    `clienti_ritorno` INT,
    `clienti_una_volta` INT,
    `totale_clienti` INT,
    `tasso_retention_percent` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_cross_selling_promozioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_cross_selling_promozioni` (
    `id_promozione` INT,
    `promozione` INT,
    `scontrini_con_promozione` INT,
    `scontrini_con_altri_prodotti` INT,
    `percentuale_cross_selling` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_customer_lifetime_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_customer_lifetime_value` (
    `id_cliente` INT,
    `nome` INT,
    `cognome` INT,
    `totale_speso` INT,
    `numero_acquisti` INT,
    `spesa_media_per_acquisto` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_distribuzione_peso_volume_scaffali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_distribuzione_peso_volume_scaffali` (
    `id_scaffale` INT,
    `tipo` INT,
    `peso_totale` INT,
    `volume_totale` INT,
    `utilizzo_peso_percent` INT,
    `utilizzo_volume_percent` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_efficienza_casse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_efficienza_casse` (
    `id_cassa` INT,
    `tipo_cassa` INT,
    `numero_scontrini` INT,
    `ricavi_totali` INT,
    `euro_per_ora` INT,
    `scontrini_per_ora` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_efficienza_mq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_efficienza_mq` (
    `id_edificio` INT,
    `nome_edificio` INT,
    `superficie_mq` INT,
    `ricavi_totali` INT,
    `ricavi_per_mq` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_fornitori_affidabili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_fornitori_affidabili` (
    `id_fornitore` INT,
    `nome_fornitore` INT,
    `affidabilita` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_fornitori_convenienti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_fornitori_convenienti` (
    `id_fornitore` INT,
    `nome_fornitore` INT,
    `prezzo_medio_offerta` INT,
    `prezzo_medio_vendita` INT,
    `margine_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_frequenza_vendita_prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_frequenza_vendita_prodotto` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `frequenza_vendita` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_impatto_promozioni_vendite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_impatto_promozioni_vendite` (
    `stato_promozione` INT,
    `totale_quantita` INT,
    `ricavi_totali` INT,
    `sconto_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_margine_lordo_prodotti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_margine_lordo_prodotti` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `prezzo_medio_vendita` INT,
    `prezzo_medio_acquisto` INT,
    `margine_lordo_unitario` INT,
    `vendite_totali` INT,
    `margine_totale` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_performance_edifici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_performance_edifici` (
    `id_edificio` INT,
    `nome_edificio` INT,
    `indirizzo` INT,
    `ricavi_totali` INT,
    `numero_scontrini` INT,
    `carrello_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_performance_marche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_performance_marche` (
    `id_marca` INT,
    `nome_marca` INT,
    `quantita_venduta` INT,
    `ricavi_totali` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_performance_produttori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_performance_produttori` (
    `id_produttore` INT,
    `nome_produttore` INT,
    `quantita_venduta` INT,
    `ricavi_totali` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_performance_titoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_performance_titoli` (
    `nome_titolo` INT,
    `numero_dipendenti` INT,
    `ricavi_totali` INT,
    `media_vendite_per_dipendente` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_picchi_carico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_picchi_carico` (
    `data_documento` INT,
    `ora` INT,
    `numero_scontrini` INT,
    `cassieri_attivi` INT,
    `scontrini_per_cassiere` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prezzo_vs_volumi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prezzo_vs_volumi` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `prezzo_medio_acquisto` INT,
    `quantita_venduta` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prodotti_associati`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prodotti_associati` (
    `prodotto_1` INT,
    `prodotto_2` INT,
    `frequenza` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prodotti_cari_ma_lenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prodotti_cari_ma_lenti` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `prezzo_medio_vendita` INT,
    `quantita_venduta` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prodotti_meno_venduti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prodotti_meno_venduti` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `totale_venduto` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prodotti_piu_venduti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prodotti_piu_venduti` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `totale_venduto` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prodotti_stockout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prodotti_stockout` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `volte_stockout` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_produttivita_ruolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_produttivita_ruolo` (
    `id_ruolo` INT,
    `nome_ruolo` INT,
    `numero_dipendenti` INT,
    `stipendio_medio` INT,
    `ricavi_totali` INT,
    `ricavi_per_dipendente` INT,
    `rapporto_stipendio_produttivita` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_promozioni_vs_vendite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_promozioni_vs_vendite` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `numero_promozioni` INT,
    `quantita_venduta` INT,
    `ricavi_generati` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_quantita_venduta_prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_quantita_venduta_prodotto` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `quantita_totale` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_redditivita_per_lavoro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_redditivita_per_lavoro` (
    `lavoro` INT,
    `ricavo_totale` INT,
    `spesa_media` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_redditivita_per_sesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_redditivita_per_sesso` (
    `sesso` INT,
    `ricavo_totale` INT,
    `spesa_media` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavi_per_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavi_per_categoria` (
    `id_categoria` INT,
    `nome_categoria` INT,
    `ricavi_totali` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavi_per_sottocategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavi_per_sottocategoria` (
    `id_sottocategoria` INT,
    `nome_sottocategoria` INT,
    `ricavi_totali` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavi_reparti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavi_reparti` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavo_per_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavo_per_categoria` (
    `id_categoria` INT,
    `nome_categoria` INT,
    `ricavo_categoria` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavo_per_prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavo_per_prodotto` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `ricavo_prodotto` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavo_totale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavo_totale` (`ricavo_totale` INT);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_roi_promozioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_roi_promozioni` (
    `id_promozione` INT,
    `nome` INT,
    `data_inizio` INT,
    `data_fine` INT,
    `ricavi_lordi` INT,
    `valore_sconti` INT,
    `ricavi_netto` INT,
    `roi_stimato` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_rotazione_alimentare_vs_non`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_rotazione_alimentare_vs_non` (
    `tipo_prodotto` INT,
    `vendite_totali` INT,
    `giacenza_media` INT,
    `tasso_rotazione` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_rotazione_magazzino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_rotazione_magazzino` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `vendite_totali` INT,
    `giacenza_media` INT,
    `tasso_rotazione` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_sconto_medio_prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_sconto_medio_prodotto` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `sconto_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_sconto_medio_totale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_sconto_medio_totale` (`sconto_medio_totale` INT);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_sottocategorie_low_performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_sottocategorie_low_performance` (
    `id_sottocategoria` INT,
    `nome_sottocategoria` INT,
    `numero_scontrini` INT,
    `ricavi_totali` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_spesa_per_eta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_spesa_per_eta` (
    `fascia_eta` INT,
    `ricavo_totale` INT,
    `spesa_media` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_tempo_consegna_fornitori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_tempo_consegna_fornitori` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_utilizzo_scaffali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_utilizzo_scaffali` (
    `id_scaffale` INT,
    `tipo` INT,
    `capacita_peso` INT,
    `capacita_volume` INT,
    `peso_totale` INT,
    `volume_totale` INT,
    `utilizzo_peso_percent` INT,
    `utilizzo_volume_percent` INT,
    `stato_scaffale` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_vendite_giornaliere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_vendite_giornaliere` (
    `giorno` INT,
    `totale_giornaliero` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_vendite_mensili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_vendite_mensili` (
    `anno` INT,
    `mese` INT,
    `totale_mensile` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_vendite_settimanali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_vendite_settimanali` (
    `anno_settimana` INT,
    `totale_settimanale` INT
);

-- -----------------------------------------------------
-- function calcola_totale_scontrino
-- -----------------------------------------------------

DELIMITER $$

USE `supermercato` $$

CREATE DEFINER=`root`@`localhost` FUNCTION `calcola_totale_scontrino`(p_id_documento INT) RETURNS decimal(10,2)
    READS SQL DATA
    DETERMINISTIC
BEGIN
    DECLARE totale DECIMAL(10,2);
    
    SELECT COALESCE(SUM(
        prezzo_unitario * quantita * (1 - sconto_percentuale/100)
    ), 0)
    INTO totale
    FROM dettagli_scontrino
    WHERE id_documento = p_id_documento;
    
    RETURN totale;
END$$

DELIMITER;

-- -----------------------------------------------------
-- function verifica_disponibilita_prodotto
-- -----------------------------------------------------

DELIMITER $$

USE `supermercato` $$

CREATE DEFINER=`root`@`localhost` FUNCTION `verifica_disponibilita_prodotto`(p_id_prodotto INT) RETURNS int
    READS SQL DATA
    DETERMINISTIC
BEGIN
    DECLARE quantita_totale INT;
    
    SELECT COALESCE(SUM(quantita), 0)
    INTO quantita_totale
    FROM giacenze g
    JOIN lotti l ON g.id_lotto = l.id_lotto
    WHERE l.id_prodotto = p_id_prodotto;
    
    RETURN quantita_totale;
END$$

DELIMITER;

-- -----------------------------------------------------
-- procedure verifica_integrita_database
-- -----------------------------------------------------

DELIMITER $$

USE `supermercato` $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `verifica_integrita_database`()
BEGIN
    DECLARE errori_trovati INT DEFAULT 0;
    DECLARE messaggio VARCHAR(500);
    
    -- Verifica dipendenti minorenni
    SELECT COUNT(*) INTO @count_err
    FROM dipendenti
    WHERE TIMESTAMPDIFF(YEAR, data_nascita, CURDATE()) < 18;
    
    IF @count_err > 0 THEN
        SET errori_trovati = errori_trovati + 1;
        SELECT CONCAT('Trovati ', @count_err, ' dipendenti minorenni') INTO messaggio;
        SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT = messaggio;
    END IF;

    -- Verifica prodotti scaduti (using lotti)
    SELECT COUNT(*) INTO @count_err
    FROM lotti
    WHERE data_scadenza < CURDATE();
    
    IF @count_err > 0 THEN
        SET errori_trovati = errori_trovati + 1;
        SELECT CONCAT('Trovati ', @count_err, ' lotti scaduti') INTO messaggio;
        SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT = messaggio;
    END IF;

    -- Verifica capacità scaffali (using giacenze)
    SELECT COUNT(*) INTO @count_err
    FROM (
        SELECT s.id_scaffale
        FROM scaffali s
        JOIN giacenze g ON s.id_scaffale = g.id_scaffale
        JOIN lotti l ON g.id_lotto = l.id_lotto
        JOIN prodotti p ON l.id_prodotto = p.id_prodotto
        GROUP BY s.id_scaffale
        HAVING SUM(p.peso_kg * g.quantita) > s.capacita_peso 
        OR SUM(p.volume_cm3 * g.quantita) > s.capacita_volume
    ) as scaffali_overload;

    IF @count_err > 0 THEN
        SET errori_trovati = errori_trovati + 1;
        SELECT CONCAT('Trovati ', @count_err, ' scaffali sovraccarichi') INTO messaggio;
        SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT = messaggio;
    END IF;
    
    SELECT errori_trovati as numero_errori_trovati;
END$$

DELIMITER;

-- -----------------------------------------------------
-- View `supermercato`.`vw_efficienza_casse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_efficienza_casse`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_efficienza_casse` AS
select
    `c`.`id_cassa` AS `id_cassa`,
    `c`.`tipo` AS `tipo_cassa`,
    count(`d`.`id_documento`) AS `numero_scontrini`,
    sum(`d`.`importo`) AS `ricavi_totali`,
    round(
        (
            sum(`d`.`importo`) / count(
                distinct concat(
                    `d`.`data_documento`,
                    hour(`d`.`ora_documento`)
                )
            )
        ),
        2
    ) AS `euro_per_ora`,
    round(
        (
            count(`d`.`id_documento`) / count(
                distinct concat(
                    `d`.`data_documento`,
                    hour(`d`.`ora_documento`)
                )
            )
        ),
        2
    ) AS `scontrini_per_ora`
from (
        `supermercato`.`casse` `c`
        join `supermercato`.`documenti` `d` on (
            (
                `c`.`id_cassa` = `d`.`id_cassa`
            )
        )
    )
where (
        `d`.`tipo_documento` = 'Scontrino'
    )
group by
    `c`.`id_cassa`,
    `c`.`tipo`
order by `euro_per_ora` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_efficienza_mq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_efficienza_mq`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_efficienza_mq` AS
select
    `e`.`id_edificio` AS `id_edificio`,
    `e`.`nome_edificio` AS `nome_edificio`,
    `e`.`superficie_mq` AS `superficie_mq`,
    sum(`d`.`importo`) AS `ricavi_totali`,
    round(
        (
            sum(`d`.`importo`) / `e`.`superficie_mq`
        ),
        2
    ) AS `ricavi_per_mq`
from (
        (
            (
                `supermercato`.`edifici` `e`
                join `supermercato`.`uffici` `u` on (
                    (
                        `e`.`id_edificio` = `u`.`id_edificio`
                    )
                )
            )
            join `supermercato`.`dipendenti` `p` on (
                (
                    `u`.`id_ufficio` = `p`.`id_ufficio`
                )
            )
        )
        join `supermercato`.`documenti` `d` on (
            (
                `p`.`id_dipendente` = `d`.`id_dipendente`
            )
        )
    )
where (
        `d`.`tipo_documento` = 'Scontrino'
    )
group by
    `e`.`id_edificio`,
    `e`.`nome_edificio`,
    `e`.`superficie_mq`
order by `ricavi_per_mq` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_fornitori_affidabili`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_fornitori_affidabili`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_fornitori_affidabili` AS
select
    `f`.`id_fornitore` AS `id_fornitore`,
    `f`.`nome_fornitore` AS `nome_fornitore`,
    `f`.`affidabilita` AS `affidabilita`
from `supermercato`.`fornitori` `f`
order by `f`.`affidabilita` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_fornitori_convenienti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_fornitori_convenienti`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_fornitori_convenienti` AS
select
    `f`.`id_fornitore` AS `id_fornitore`,
    `f`.`nome_fornitore` AS `nome_fornitore`,
    round(avg(`cf`.`prezzo_offerta`), 2) AS `prezzo_medio_offerta`,
    round(avg(`p`.`prezzo_vendita`), 2) AS `prezzo_medio_vendita`,
    round(
        (
            avg(`p`.`prezzo_vendita`) - avg(`cf`.`prezzo_offerta`)
        ),
        2
    ) AS `margine_medio`
from (
        (
            `supermercato`.`fornitori` `f`
            join `supermercato`.`catalogo_fornitori` `cf` on (
                (
                    `f`.`id_fornitore` = `cf`.`id_fornitore`
                )
            )
        )
        join `supermercato`.`prodotti` `p` on (
            (
                `cf`.`id_prodotto` = `p`.`id_prodotto`
            )
        )
    )
group by
    `f`.`id_fornitore`,
    `f`.`nome_fornitore`
order by `margine_medio` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_frequenza_vendita_prodotto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_frequenza_vendita_prodotto`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_frequenza_vendita_prodotto` AS
select
    `p`.`id_prodotto` AS `id_prodotto`,
    `p`.`nome_prodotto` AS `nome_prodotto`,
    count(distinct `ds`.`id_documento`) AS `frequenza_vendita`
from (
        `supermercato`.`dettagli_scontrino` `ds`
        join `supermercato`.`prodotti` `p` on (
            (
                `ds`.`id_prodotto` = `p`.`id_prodotto`
            )
        )
    )
group by
    `p`.`id_prodotto`,
    `p`.`nome_prodotto`
order by `frequenza_vendita` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_impatto_promozioni_vendite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_impatto_promozioni_vendite`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_impatto_promozioni_vendite` AS
select (
        case
            when (
                (`ds`.`sconto_percentuale` > 0)
                or (
                    `pp`.`id_promozione` is not null
                )
            ) then 'In Promozione'
            else 'Non in Promozione'
        end
    ) AS `stato_promozione`,
    sum(`ds`.`quantita`) AS `totale_quantita`,
    sum(
        (
            (
                `ds`.`quantita` * `ds`.`prezzo_unitario`
            ) * (
                1 - (
                    `ds`.`sconto_percentuale` / 100
                )
            )
        )
    ) AS `ricavi_totali`,
    avg(`ds`.`sconto_percentuale`) AS `sconto_medio`
from (
        (
            `supermercato`.`dettagli_scontrino` `ds`
            join `supermercato`.`prodotti` `p` on (
                (
                    `ds`.`id_prodotto` = `p`.`id_prodotto`
                )
            )
        )
        left join `supermercato`.`promozioni_prodotti` `pp` on (
            (
                `p`.`id_prodotto` = `pp`.`id_prodotto`
            )
        )
    )
group by
    `stato_promozione`;

-- -----------------------------------------------------
-- View `supermercato`.`vw_margine_lordo_prodotti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_margine_lordo_prodotti`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_margine_lordo_prodotti` AS
select
    `p`.`id_prodotto` AS `id_prodotto`,
    `p`.`nome_prodotto` AS `nome_prodotto`,
    round(avg(`p`.`prezzo_vendita`), 2) AS `prezzo_medio_vendita`,
    round(avg(`cf`.`prezzo_offerta`), 2) AS `prezzo_medio_acquisto`,
    round(
        (
            avg(`p`.`prezzo_vendita`) - avg(`cf`.`prezzo_offerta`)
        ),
        2
    ) AS `margine_lordo_unitario`,
    sum(`ds`.`quantita`) AS `vendite_totali`,
    round(
        (
            (
                avg(`p`.`prezzo_vendita`) - avg(`cf`.`prezzo_offerta`)
            ) * sum(`ds`.`quantita`)
        ),
        2
    ) AS `margine_totale`
from (
        (
            `supermercato`.`prodotti` `p`
            left join `supermercato`.`catalogo_fornitori` `cf` on (
                (
                    `p`.`id_prodotto` = `cf`.`id_prodotto`
                )
            )
        )
        left join `supermercato`.`dettagli_scontrino` `ds` on (
            (
                `p`.`id_prodotto` = `ds`.`id_prodotto`
            )
        )
    )
group by
    `p`.`id_prodotto`,
    `p`.`nome_prodotto`
order by `margine_totale` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_performance_edifici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_performance_edifici`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_performance_edifici` AS
select
    `e`.`id_edificio` AS `id_edificio`,
    `e`.`nome_edificio` AS `nome_edificio`,
    `e`.`indirizzo` AS `indirizzo`,
    sum(`d`.`importo`) AS `ricavi_totali`,
    count(`d`.`id_documento`) AS `numero_scontrini`,
    round(
        (
            sum(`d`.`importo`) / count(`d`.`id_documento`)
        ),
        2
    ) AS `carrello_medio`
from (
        (
            (
                `supermercato`.`edifici` `e`
                join `supermercato`.`uffici` `u` on (
                    (
                        `e`.`id_edificio` = `u`.`id_edificio`
                    )
                )
            )
            join `supermercato`.`dipendenti` `p` on (
                (
                    `u`.`id_ufficio` = `p`.`id_ufficio`
                )
            )
        )
        join `supermercato`.`documenti` `d` on (
            (
                `p`.`id_dipendente` = `d`.`id_dipendente`
            )
        )
    )
where (
        `d`.`tipo_documento` = 'Scontrino'
    )
group by
    `e`.`id_edificio`,
    `e`.`nome_edificio`,
    `e`.`indirizzo`
order by `ricavi_totali` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_performance_marche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_performance_marche`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_performance_marche` AS
select
    `m`.`id_marca` AS `id_marca`,
    `m`.`nome_marca` AS `nome_marca`,
    sum(`ds`.`quantita`) AS `quantita_venduta`,
    sum(
        (
            (
                `ds`.`quantita` * `ds`.`prezzo_unitario`
            ) * (
                1 - (
                    `ds`.`sconto_percentuale` / 100
                )
            )
        )
    ) AS `ricavi_totali`
from (
        (
            `supermercato`.`prodotti` `p`
            join `supermercato`.`marche` `m` on (
                (
                    `p`.`id_marca` = `m`.`id_marca`
                )
            )
        )
        join `supermercato`.`dettagli_scontrino` `ds` on (
            (
                `p`.`id_prodotto` = `ds`.`id_prodotto`
            )
        )
    )
group by
    `m`.`id_marca`,
    `m`.`nome_marca`
order by `ricavi_totali` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_performance_produttori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_performance_produttori`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_performance_produttori` AS
select
    `pr`.`id_produttore` AS `id_produttore`,
    `pr`.`nome_produttore` AS `nome_produttore`,
    sum(`ds`.`quantita`) AS `quantita_venduta`,
    sum(
        (
            (
                `ds`.`quantita` * `ds`.`prezzo_unitario`
            ) * (
                1 - (
                    `ds`.`sconto_percentuale` / 100
                )
            )
        )
    ) AS `ricavi_totali`
from (
        (
            (
                `supermercato`.`prodotti` `p`
                join `supermercato`.`marche` `m` on (
                    (
                        `p`.`id_marca` = `m`.`id_marca`
                    )
                )
            )
            join `supermercato`.`produttori` `pr` on (
                (
                    `m`.`id_produttore` = `pr`.`id_produttore`
                )
            )
        )
        join `supermercato`.`dettagli_scontrino` `ds` on (
            (
                `p`.`id_prodotto` = `ds`.`id_prodotto`
            )
        )
    )
group by
    `pr`.`id_produttore`,
    `pr`.`nome_produttore`
order by `ricavi_totali` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_performance_titoli`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_performance_titoli`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_performance_titoli` AS
select
    `t`.`nome_titolo` AS `nome_titolo`,
    count(distinct `dt`.`id_dipendente`) AS `numero_dipendenti`,
    sum(`d`.`importo`) AS `ricavi_totali`,
    round(avg(`d`.`importo`), 2) AS `media_vendite_per_dipendente`
from (
        (
            (
                `supermercato`.`dipendenti_titoli` `dt`
                join `supermercato`.`titoli` `t` on (
                    (
                        `dt`.`id_titolo` = `t`.`id_titolo`
                    )
                )
            )
            join `supermercato`.`dipendenti` `dp` on (
                (
                    `dt`.`id_dipendente` = `dp`.`id_dipendente`
                )
            )
        )
        join `supermercato`.`documenti` `d` on (
            (
                `dp`.`id_dipendente` = `d`.`id_dipendente`
            )
        )
    )
where (
        `d`.`tipo_documento` = 'Scontrino'
    )
group by
    `t`.`id_titolo`,
    `t`.`nome_titolo`
order by `ricavi_totali` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_picchi_carico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_picchi_carico`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_picchi_carico` AS
select
    `d`.`data_documento` AS `data_documento`,
    hour(`d`.`ora_documento`) AS `ora`,
    count(`d`.`id_documento`) AS `numero_scontrini`,
    count(distinct `d`.`id_dipendente`) AS `cassieri_attivi`,
    round(
        (
            count(`d`.`id_documento`) / nullif(
                count(distinct `d`.`id_dipendente`),
                0
            )
        ),
        2
    ) AS `scontrini_per_cassiere`
from `supermercato`.`documenti` `d`
where (
        `d`.`tipo_documento` = 'Scontrino'
    )
group by
    `d`.`data_documento`,
    hour(`d`.`ora_documento`)
order by `numero_scontrini` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_prezzo_vs_volumi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_prezzo_vs_volumi`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_prezzo_vs_volumi` AS
select
    `p`.`id_prodotto` AS `id_prodotto`,
    `p`.`nome_prodotto` AS `nome_prodotto`,
    round(avg(`cf`.`prezzo_offerta`), 2) AS `prezzo_medio_acquisto`,
    sum(`ds`.`quantita`) AS `quantita_venduta`
from (
        (
            `supermercato`.`prodotti` `p`
            left join `supermercato`.`catalogo_fornitori` `cf` on (
                (
                    `p`.`id_prodotto` = `cf`.`id_prodotto`
                )
            )
        )
        left join `supermercato`.`dettagli_scontrino` `ds` on (
            (
                `p`.`id_prodotto` = `ds`.`id_prodotto`
            )
        )
    )
group by
    `p`.`id_prodotto`,
    `p`.`nome_prodotto`
order by `quantita_venduta` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_prodotti_associati`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_prodotti_associati`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_prodotti_associati` AS
select
    `p1`.`nome_prodotto` AS `prodotto_1`,
    `p2`.`nome_prodotto` AS `prodotto_2`,
    count(0) AS `frequenza`
from (
        (
            (
                `supermercato`.`dettagli_scontrino` `ds1`
                join `supermercato`.`dettagli_scontrino` `ds2` on (
                    (
                        (
                            `ds1`.`id_documento` = `ds2`.`id_documento`
                        )
                        and (
                            `ds1`.`id_prodotto` < `ds2`.`id_prodotto`
                        )
                    )
                )
            )
            join `supermercato`.`prodotti` `p1` on (
                (
                    `ds1`.`id_prodotto` = `p1`.`id_prodotto`
                )
            )
        )
        join `supermercato`.`prodotti` `p2` on (
            (
                `ds2`.`id_prodotto` = `p2`.`id_prodotto`
            )
        )
    )
group by
    `p1`.`nome_prodotto`,
    `p2`.`nome_prodotto`
order by `frequenza` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_prodotti_cari_ma_lenti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_prodotti_cari_ma_lenti`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_prodotti_cari_ma_lenti` AS
select
    `p`.`id_prodotto` AS `id_prodotto`,
    `p`.`nome_prodotto` AS `nome_prodotto`,
    round(avg(`p`.`prezzo_vendita`), 2) AS `prezzo_medio_vendita`,
    sum(`ds`.`quantita`) AS `quantita_venduta`
from (
        `supermercato`.`prodotti` `p`
        left join `supermercato`.`dettagli_scontrino` `ds` on (
            (
                `p`.`id_prodotto` = `ds`.`id_prodotto`
            )
        )
    )
group by
    `p`.`id_prodotto`,
    `p`.`nome_prodotto`
having (sum(`ds`.`quantita`) < 50)
order by
    `prezzo_medio_vendita` desc,
    `quantita_venduta`;

-- -----------------------------------------------------
-- View `supermercato`.`vw_prodotti_meno_venduti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_prodotti_meno_venduti`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_prodotti_meno_venduti` AS
select
    `p`.`id_prodotto` AS `id_prodotto`,
    `p`.`nome_prodotto` AS `nome_prodotto`,
    sum(`ds`.`quantita`) AS `totale_venduto`
from (
        `supermercato`.`dettagli_scontrino` `ds`
        join `supermercato`.`prodotti` `p` on (
            (
                `ds`.`id_prodotto` = `p`.`id_prodotto`
            )
        )
    )
group by
    `p`.`id_prodotto`,
    `p`.`nome_prodotto`
order by `totale_venduto`;

-- -----------------------------------------------------
-- View `supermercato`.`vw_prodotti_piu_venduti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_prodotti_piu_venduti`;

USE `supermercato`;

CREATE
OR
REPLACE
    ALGORITHM = UNDEFINED DEFINER = `root` @`localhost` SQL SECURITY DEFINER VIEW `supermercato`.`vw_prodotti_piu_venduti` AS
select
    `p`.`id_prodotto` AS `id_prodotto`,
    `p`.`nome_prodotto` AS `nome_prodotto`,
    sum(`ds`.`quantita`) AS `totale_venduto`
from (
        `supermercato`.`dettagli_scontrino` `ds`
        join `supermercato`.`prodotti` `p` on (
            (
                `ds`.`id_prodotto` = `p`.`id_prodotto`
            )
        )
    )
group by
    `p`.`id_prodotto`,
    `p`.`nome_prodotto`
order by `totale_venduto` desc;

-- -----------------------------------------------------
-- View `supermercato`.`vw_prodotti_stockout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_prodotti_stockout`;

USE `supermercato`;

CREATE OR REPLACE VIEW `supermercato`.`vw_prodotti_stockout` AS
SELECT p.id_prodotto, p.nome_prodotto, 0 as volte_stockout
FROM
    prodotti p
    LEFT JOIN lotti l ON p.id_prodotto = l.id_prodotto
    LEFT JOIN giacenze g ON l.id_lotto = g.id_lotto
GROUP BY
    p.id_prodotto,
    p.nome_prodotto
HAVING
    COALESCE(SUM(g.quantita), 0) = 0;

-- -----------------------------------------------------
-- View `supermercato`.`vw_ricavi_reparti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_ricavi_reparti`;

USE `supermercato`;

CREATE OR REPLACE VIEW `supermercato`.`vw_ricavi_reparti` AS
SELECT r.id_reparto, r.nome_reparto, SUM(
        ds.prezzo_unitario * ds.quantita
    ) as ricavi_totali
FROM
    reparti r
    JOIN scaffali s ON r.id_reparto = s.id_reparto
    JOIN giacenze g ON s.id_scaffale = g.id_scaffale
    JOIN lotti l ON g.id_lotto = l.id_lotto
    JOIN prodotti p ON l.id_prodotto = p.id_prodotto
    JOIN dettagli_scontrino ds ON p.id_prodotto = ds.id_prodotto
GROUP BY
    r.id_reparto,
    r.nome_reparto;

-- -----------------------------------------------------
-- View `supermercato`.`vw_rotazione_alimentare_vs_non`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_rotazione_alimentare_vs_non`;

USE `supermercato`;

CREATE OR REPLACE VIEW `supermercato`.`vw_rotazione_alimentare_vs_non` AS
SELECT
    CASE
        WHEN p.is_alimentare = 1 THEN 'Alimentare'
        ELSE 'Non Alimentare'
    END as tipo_prodotto,
    SUM(ds.quantita) as vendite_totali,
    COALESCE(SUM(g.quantita), 0) as giacenza_media,
    CASE
        WHEN COALESCE(SUM(g.quantita), 0) = 0 THEN 0
        ELSE SUM(ds.quantita) / SUM(g.quantita)
    END as tasso_rotazione
FROM
    prodotti p
    LEFT JOIN dettagli_scontrino ds ON p.id_prodotto = ds.id_prodotto
    LEFT JOIN lotti l ON p.id_prodotto = l.id_prodotto
    LEFT JOIN giacenze g ON l.id_lotto = g.id_lotto
GROUP BY
    tipo_prodotto;

-- -----------------------------------------------------
-- View `supermercato`.`vw_rotazione_magazzino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_rotazione_magazzino`;

USE `supermercato`;

CREATE OR REPLACE VIEW `supermercato`.`vw_rotazione_magazzino` AS
SELECT
    p.id_prodotto,
    p.nome_prodotto,
    SUM(ds.quantita) as vendite_totali,
    COALESCE(SUM(g.quantita), 0) as giacenza_media,
    CASE
        WHEN COALESCE(SUM(g.quantita), 0) = 0 THEN 0
        ELSE SUM(ds.quantita) / SUM(g.quantita)
    END as tasso_rotazione
FROM
    prodotti p
    LEFT JOIN dettagli_scontrino ds ON p.id_prodotto = ds.id_prodotto
    LEFT JOIN lotti l ON p.id_prodotto = l.id_prodotto
    LEFT JOIN giacenze g ON l.id_lotto = g.id_lotto
GROUP BY
    p.id_prodotto,
    p.nome_prodotto;

-- -----------------------------------------------------
-- View `supermercato`.`vw_utilizzo_scaffali`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supermercato`.`vw_utilizzo_scaffali`;

USE `supermercato`;

CREATE OR REPLACE VIEW `supermercato`.`vw_utilizzo_scaffali` AS
SELECT
    s.id_scaffale,
    s.tipo,
    s.capacita_peso,
    s.capacita_volume,
    COALESCE(
        SUM(p.peso_kg * g.quantita),
        0
    ) as peso_totale,
    COALESCE(
        SUM(p.volume_cm3 * g.quantita),
        0
    ) as volume_totale,
    COALESCE(
        (
            SUM(p.peso_kg * g.quantita) / s.capacita_peso
        ) * 100,
        0
    ) as utilizzo_peso_percent,
    COALESCE(
        (
            SUM(p.volume_cm3 * g.quantita) / s.capacita_volume
        ) * 100,
        0
    ) as utilizzo_volume_percent,
    CASE
        WHEN (
            SUM(p.peso_kg * g.quantita) / s.capacita_peso
        ) > 0.9 THEN 'Pieno'
        WHEN (
            SUM(p.peso_kg * g.quantita) / s.capacita_peso
        ) > 0.5 THEN 'Medio'
        ELSE 'Vuoto'
    END as stato_scaffale
FROM
    scaffali s
    LEFT JOIN giacenze g ON s.id_scaffale = g.id_scaffale
    LEFT JOIN lotti l ON g.id_lotto = l.id_lotto
    LEFT JOIN prodotti p ON l.id_prodotto = p.id_prodotto
GROUP BY
    s.id_scaffale;

-- -----------------------------------------------------
-- Trigger `supermercato`.`before_insert_promozioni_date`
-- -----------------------------------------------------
TRIGGER `supermercato`.`before_insert_promozioni_date` BEFORE
INSERT
    ON `supermercato`.`promozioni` FOR EACH ROW BEGIN IF NEW.data_fine <= NEW.data_inizio THEN SIGNAL SQLSTATE '45000'
SET
    MESSAGE_TEXT = 'Errore: La data di fine promozione deve essere successiva alla data di inizio';

END IF;

END $$

USE `supermercato` $$

CREATE
DEFINER=`root`@`localhost`
TRIGGER `supermercato`.`before_update_promozioni_date`
BEFORE UPDATE ON `supermercato`.`promozioni`
FOR EACH ROW
BEGIN
    IF NEW.data_fine <= NEW.data_inizio THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Errore: La data di fine promozione deve essere successiva alla data di inizio';
    END IF;
END$$

USE `supermercato` $$

CREATE
DEFINER=`root`@`localhost`
TRIGGER `supermercato`.`before_insert_promozioni_prodotti_unica`
BEFORE INSERT ON `supermercato`.`promozioni_prodotti`
FOR EACH ROW
BEGIN
    DECLARE promozioni_attive INT;
    DECLARE data_inizio_nuova DATE;
    DECLARE data_fine_nuova DATE;
    
    -- Ottieni le date della promozione
    SELECT data_inizio, data_fine 
    INTO data_inizio_nuova, data_fine_nuova
    FROM promozioni
    WHERE id_promozione = NEW.id_promozione;
    
    -- Verifica sovrapposizioni con altre promozioni
    SELECT COUNT(*) INTO promozioni_attive
    FROM promozioni_prodotti pp
    INNER JOIN promozioni p ON pp.id_promozione = p.id_promozione
    WHERE pp.id_prodotto = NEW.id_prodotto
    AND pp.id_promozione != NEW.id_promozione
    AND (
        (data_inizio_nuova BETWEEN p.data_inizio AND p.data_fine)
        OR (data_fine_nuova BETWEEN p.data_inizio AND p.data_fine)
        OR (p.data_inizio BETWEEN data_inizio_nuova AND data_fine_nuova)
    );
    
    IF promozioni_attive > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Errore: Il prodotto ha già una promozione attiva in questo periodo';
    END IF;
END$$

USE `supermercato` $$

CREATE TRIGGER `supermercato`.`before_insert_giacenze_capacita` BEFORE INSERT ON `supermercato`.`giacenze`
FOR EACH ROW
BEGIN
    DECLARE peso_attuale DECIMAL(10,2);
    DECLARE volume_attuale DECIMAL(10,2);
    DECLARE peso_prodotto DECIMAL(6,3);
    DECLARE volume_prodotto INT;
    DECLARE capacita_peso_scaffale DECIMAL(10,2);
    DECLARE capacita_volume_scaffale DECIMAL(10,2);

    -- Get product dimensions
    SELECT peso_kg, volume_cm3 INTO peso_prodotto, volume_prodotto
    FROM prodotti p
    JOIN lotti l ON p.id_prodotto = l.id_prodotto
    WHERE l.id_lotto = NEW.id_lotto;

    -- Get shelf capacity
    SELECT capacita_peso, capacita_volume INTO capacita_peso_scaffale, capacita_volume_scaffale
    FROM scaffali
    WHERE id_scaffale = NEW.id_scaffale;

    -- Calculate current usage
    SELECT COALESCE(SUM(p.peso_kg * g.quantita), 0), COALESCE(SUM(p.volume_cm3 * g.quantita), 0)
    INTO peso_attuale, volume_attuale
    FROM giacenze g
    JOIN lotti l ON g.id_lotto = l.id_lotto
    JOIN prodotti p ON l.id_prodotto = p.id_prodotto
    WHERE g.id_scaffale = NEW.id_scaffale;

    -- Check capacity
    IF (peso_attuale + (peso_prodotto * NEW.quantita)) > capacita_peso_scaffale THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Errore: Capacità peso scaffale superata';
    END IF;

    IF (volume_attuale + (volume_prodotto * NEW.quantita)) > capacita_volume_scaffale THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Errore: Capacità volume scaffale superata';
    END IF;
END$$

DELIMITER;

SET SQL_MODE = @OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Trigger `supermercato`.`after_insert_dettagli_scontrino`
-- -----------------------------------------------------
DELIMITER $$

USE `supermercato` $$

CREATE TRIGGER `supermercato`.`after_insert_dettagli_scontrino` AFTER INSERT ON `supermercato`.`dettagli_scontrino`
FOR EACH ROW
BEGIN
    DECLARE qta_rimanente INT;
    DECLARE id_giacenza_curr INT;
    DECLARE qta_giacenza_curr INT;
    DECLARE finished INT DEFAULT 0;
    
    -- Cursore per selezionare le giacenze ordinate per data di scadenza (FIFO)
    DECLARE cur_giacenze CURSOR FOR 
        SELECT g.id_giacenza, g.quantita
        FROM giacenze g
        JOIN lotti l ON g.id_lotto = l.id_lotto
        WHERE l.id_prodotto = NEW.id_prodotto
        ORDER BY l.data_scadenza ASC;
        
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET finished = 1;
    
    SET qta_rimanente = NEW.quantita;
    
    OPEN cur_giacenze;
    
    read_loop: LOOP
        FETCH cur_giacenze INTO id_giacenza_curr, qta_giacenza_curr;
        
        IF finished = 1 THEN
            LEAVE read_loop;
        END IF;
        
        IF qta_rimanente > 0 THEN
            IF qta_giacenza_curr >= qta_rimanente THEN
                -- La giacenza corrente è sufficiente
                UPDATE giacenze 
                SET quantita = quantita - qta_rimanente 
                WHERE id_giacenza = id_giacenza_curr;
                
                SET qta_rimanente = 0;
                LEAVE read_loop;
            ELSE
                -- La giacenza corrente non è sufficiente, la azzeriamo e continuiamo
                UPDATE giacenze 
                SET quantita = 0 
                WHERE id_giacenza = id_giacenza_curr;
                
                SET qta_rimanente = qta_rimanente - qta_giacenza_curr;
            END IF;
        END IF;
    END LOOP;
    
    CLOSE cur_giacenze;
    
    -- Se dopo il loop c'è ancora quantità da scalare, significa che non c'è abbastanza stock
    IF qta_rimanente > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Errore: Giacenza insufficiente per soddisfare la vendita';
    END IF;
    
END$$

DELIMITER;

-- -----------------------------------------------------
-- Procedure `supermercato`.`ricevi_prodotto_da_ordine`
-- -----------------------------------------------------
DELIMITER $$

USE `supermercato` $$

CREATE PROCEDURE `ricevi_prodotto_da_ordine`(
    IN p_id_ordine INT,
    IN p_id_prodotto INT,
    IN p_codice_lotto VARCHAR(50),
    IN p_data_scadenza DATE,
    IN p_data_produzione DATE,
    IN p_id_scaffale INT
)
BEGIN
    DECLARE v_quantita INT;
    DECLARE v_lotto_id INT;
    
    -- Ottieni la quantità dall'ordine
    SELECT quantita INTO v_quantita
    FROM dettagli_ordine
    WHERE id_ordine = p_id_ordine AND id_prodotto = p_id_prodotto;
    
    IF v_quantita IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Errore: Prodotto non trovato nell''ordine specificato';
    END IF;
    
    -- Crea il Lotto
    INSERT INTO lotti (codice_lotto, id_prodotto, data_produzione, data_scadenza)
    VALUES (p_codice_lotto, p_id_prodotto, p_data_produzione, p_data_scadenza);
    
    SET v_lotto_id = LAST_INSERT_ID();
    
    -- Crea la Giacenza
    INSERT INTO giacenze (id_lotto, id_scaffale, quantita)
    VALUES (v_lotto_id, p_id_scaffale, v_quantita);
    
    -- Aggiorna lo stato dell'ordine a 'Consegnato' (Semplificazione: assume consegna completa)
    UPDATE ordini_fornitore SET stato = 'Consegnato' WHERE id_ordine = p_id_ordine;
    
END$$

DELIMITER;