-- MySQL Script generated by MySQL Workbench
-- Version: 1.1
-- Model: Supermercato    Version: 1.0

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @@SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema supermercato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supermercato` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `supermercato`;

-- -----------------------------------------------------
-- Table `supermercato`.`edifici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`edifici` (
    `id_edificio` INT NOT NULL AUTO_INCREMENT,
    `nome_edificio` VARCHAR(100) NOT NULL,
    `indirizzo` VARCHAR(255) NULL,
    `superficie_mq` INT NULL,
    `funzione_principale` ENUM(
        'Punto Vendita',
        'Magazzino',
        'Sede'
    ) NOT NULL,
    PRIMARY KEY (`id_edificio`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`uffici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`uffici` (
    `id_ufficio` INT NOT NULL AUTO_INCREMENT,
    `nome_ufficio` VARCHAR(100) NOT NULL,
    `piano` INT NULL,
    `id_edificio` INT NOT NULL,
    PRIMARY KEY (`id_ufficio`),
    INDEX `fk_uffici_edifici_idx` (`id_edificio` ASC) VISIBLE,
    CONSTRAINT `fk_uffici_edifici` FOREIGN KEY (`id_edificio`) REFERENCES `supermercato`.`edifici` (`id_edificio`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`ruoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`ruoli` (
    `id_ruolo` INT NOT NULL AUTO_INCREMENT,
    `nome_ruolo` VARCHAR(100) NOT NULL,
    `descrizione` TEXT NULL,
    `livello_autorizzazione` ENUM(
        'Operativo',
        'Supervisione',
        'Manageriale'
    ) NOT NULL,
    PRIMARY KEY (`id_ruolo`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`dipendenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`dipendenti` (
    `id_dipendente` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(100) NOT NULL,
    `cognome` VARCHAR(100) NOT NULL,
    `data_nascita` DATE NOT NULL,
    `email` VARCHAR(150) NULL,
    `telefono` VARCHAR(20) NULL,
    `data_assunzione` DATE NOT NULL,
    `stipendio` DECIMAL(10, 2) NULL,
    `id_ruolo` INT NOT NULL,
    `id_ufficio` INT NOT NULL,
    PRIMARY KEY (`id_dipendente`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    INDEX `fk_dipendenti_ruoli_idx` (`id_ruolo` ASC) VISIBLE,
    INDEX `fk_dipendenti_uffici_idx` (`id_ufficio` ASC) VISIBLE,
    CONSTRAINT `fk_dipendenti_ruoli` FOREIGN KEY (`id_ruolo`) REFERENCES `supermercato`.`ruoli` (`id_ruolo`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_dipendenti_uffici` FOREIGN KEY (`id_ufficio`) REFERENCES `supermercato`.`uffici` (`id_ufficio`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`titoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`titoli` (
    `id_titolo` INT NOT NULL AUTO_INCREMENT,
    `nome_titolo` VARCHAR(100) NOT NULL,
    `ente_emittente` VARCHAR(100) NULL,
    `data_conseguimento` DATE NULL,
    `data_scadenza` DATE NULL,
    `eqf` INT NULL,
    PRIMARY KEY (`id_titolo`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`dipendenti_titoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`dipendenti_titoli` (
    `id_dipendente` INT NOT NULL,
    `id_titolo` INT NOT NULL,
    PRIMARY KEY (`id_dipendente`, `id_titolo`),
    INDEX `fk_dipendenti_titoli_titoli_idx` (`id_titolo` ASC) VISIBLE,
    CONSTRAINT `fk_dipendenti_titoli_dipendenti` FOREIGN KEY (`id_dipendente`) REFERENCES `supermercato`.`dipendenti` (`id_dipendente`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_dipendenti_titoli_titoli` FOREIGN KEY (`id_titolo`) REFERENCES `supermercato`.`titoli` (`id_titolo`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`ruoli_titoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`ruoli_titoli` (
    `id_ruolo` INT NOT NULL,
    `id_titolo` INT NOT NULL,
    PRIMARY KEY (`id_ruolo`, `id_titolo`),
    INDEX `fk_ruoli_titoli_titoli_idx` (`id_titolo` ASC) VISIBLE,
    CONSTRAINT `fk_ruoli_titoli_ruoli` FOREIGN KEY (`id_ruolo`) REFERENCES `supermercato`.`ruoli` (`id_ruolo`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_ruoli_titoli_titoli` FOREIGN KEY (`id_titolo`) REFERENCES `supermercato`.`titoli` (`id_titolo`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`reparti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`reparti` (
    `id_reparto` INT NOT NULL AUTO_INCREMENT,
    `nome_reparto` VARCHAR(100) NOT NULL,
    `descrizione` TEXT NULL,
    PRIMARY KEY (`id_reparto`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`scaffali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`scaffali` (
    `id_scaffale` INT NOT NULL AUTO_INCREMENT,
    `tipo` ENUM(
        'Normale',
        'Frigorifero',
        'Congelatore'
    ) NOT NULL,
    `capacita_peso` DECIMAL(10, 2) NOT NULL,
    `capacita_volume` DECIMAL(10, 2) NOT NULL,
    `id_reparto` INT NOT NULL,
    `id_edificio` INT NOT NULL,
    PRIMARY KEY (`id_scaffale`),
    INDEX `fk_scaffali_reparti_idx` (`id_reparto` ASC) VISIBLE,
    INDEX `fk_scaffali_edifici_idx` (`id_edificio` ASC) VISIBLE,
    CONSTRAINT `fk_scaffali_reparti` FOREIGN KEY (`id_reparto`) REFERENCES `supermercato`.`reparti` (`id_reparto`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_scaffali_edifici` FOREIGN KEY (`id_edificio`) REFERENCES `supermercato`.`edifici` (`id_edificio`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`reparto_edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`reparto_edificio` (
    `id_reparto` INT NOT NULL,
    `id_edificio` INT NOT NULL,
    PRIMARY KEY (`id_reparto`, `id_edificio`),
    INDEX `fk_reparto_edificio_edifici_idx` (`id_edificio` ASC) VISIBLE,
    CONSTRAINT `fk_reparto_edificio_reparti` FOREIGN KEY (`id_reparto`) REFERENCES `supermercato`.`reparti` (`id_reparto`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_reparto_edificio_edifici` FOREIGN KEY (`id_edificio`) REFERENCES `supermercato`.`edifici` (`id_edificio`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`clienti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`clienti` (
    `id_cliente` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(100) NOT NULL,
    `cognome` VARCHAR(100) NOT NULL,
    `data_nascita` DATE NOT NULL,
    `sesso` ENUM('M', 'F', 'Altro') NULL,
    `lavoro` VARCHAR(150) NULL,
    `email` VARCHAR(150) NULL,
    `telefono` VARCHAR(20) NULL,
    `residenza` VARCHAR(255) NULL,
    `newsletter` TINYINT(1) NULL DEFAULT 0,
    PRIMARY KEY (`id_cliente`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`clienti_titoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`clienti_titoli` (
    `id_cliente` INT NOT NULL,
    `id_titolo` INT NOT NULL,
    PRIMARY KEY (`id_cliente`, `id_titolo`),
    INDEX `fk_clienti_titoli_titoli_idx` (`id_titolo` ASC) VISIBLE,
    CONSTRAINT `fk_clienti_titoli_clienti` FOREIGN KEY (`id_cliente`) REFERENCES `supermercato`.`clienti` (`id_cliente`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_clienti_titoli_titoli` FOREIGN KEY (`id_titolo`) REFERENCES `supermercato`.`titoli` (`id_titolo`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`categorie` (
    `id_categoria` INT NOT NULL AUTO_INCREMENT,
    `nome_categoria` VARCHAR(100) NOT NULL,
    `descrizione` TEXT NULL,
    PRIMARY KEY (`id_categoria`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`sottocategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`sottocategorie` (
    `id_sottocategoria` INT NOT NULL AUTO_INCREMENT,
    `nome_sottocategoria` VARCHAR(100) NOT NULL,
    `id_categoria` INT NOT NULL,
    PRIMARY KEY (`id_sottocategoria`),
    INDEX `fk_sottocategorie_categorie_idx` (`id_categoria` ASC) VISIBLE,
    CONSTRAINT `fk_sottocategorie_categorie` FOREIGN KEY (`id_categoria`) REFERENCES `supermercato`.`categorie` (`id_categoria`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`produttori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`produttori` (
    `id_produttore` INT NOT NULL AUTO_INCREMENT,
    `nome_produttore` VARCHAR(100) NOT NULL,
    `nazione` VARCHAR(50) NULL,
    `sito_web` VARCHAR(150) NULL,
    `telefono` VARCHAR(20) NULL,
    PRIMARY KEY (`id_produttore`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`marche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`marche` (
    `id_marca` INT NOT NULL AUTO_INCREMENT,
    `nome_marca` VARCHAR(100) NOT NULL,
    `id_produttore` INT NOT NULL,
    PRIMARY KEY (`id_marca`),
    INDEX `fk_marche_produttori_idx` (`id_produttore` ASC) VISIBLE,
    CONSTRAINT `fk_marche_produttori` FOREIGN KEY (`id_produttore`) REFERENCES `supermercato`.`produttori` (`id_produttore`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`prodotti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`prodotti` (
    `id_prodotto` INT NOT NULL AUTO_INCREMENT,
    `nome_prodotto` VARCHAR(150) NOT NULL,
    `prezzo_vendita` DECIMAL(10, 2) NOT NULL,
    `peso_kg` DECIMAL(6, 3) NULL,
    `volume_cm3` INT NULL,
    `id_marca` INT NOT NULL,
    `id_sottocategoria` INT NOT NULL,
    `is_alimentare` TINYINT(1) NULL DEFAULT 1,
    PRIMARY KEY (`id_prodotto`),
    INDEX `fk_prodotti_marche_idx` (`id_marca` ASC) VISIBLE,
    INDEX `fk_prodotti_sottocategorie_idx` (`id_sottocategoria` ASC) VISIBLE,
    CONSTRAINT `fk_prodotti_marche` FOREIGN KEY (`id_marca`) REFERENCES `supermercato`.`marche` (`id_marca`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_prodotti_sottocategorie` FOREIGN KEY (`id_sottocategoria`) REFERENCES `supermercato`.`sottocategorie` (`id_sottocategoria`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`lotti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`lotti` (
    `id_lotto` INT NOT NULL AUTO_INCREMENT,
    `codice_lotto` VARCHAR(50) NOT NULL,
    `id_prodotto` INT NOT NULL,
    `data_produzione` DATE NULL,
    `data_scadenza` DATE NULL,
    PRIMARY KEY (`id_lotto`),
    INDEX `fk_lotti_prodotti_idx` (`id_prodotto` ASC) VISIBLE,
    CONSTRAINT `fk_lotti_prodotti` FOREIGN KEY (`id_prodotto`) REFERENCES `supermercato`.`prodotti` (`id_prodotto`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`giacenze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`giacenze` (
    `id_giacenza` INT NOT NULL AUTO_INCREMENT,
    `id_lotto` INT NOT NULL,
    `id_scaffale` INT NOT NULL,
    `quantita` INT NOT NULL,
    `data_collocazione` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id_giacenza`),
    INDEX `fk_giacenze_lotti_idx` (`id_lotto` ASC) VISIBLE,
    INDEX `fk_giacenze_scaffali_idx` (`id_scaffale` ASC) VISIBLE,
    CONSTRAINT `fk_giacenze_lotti` FOREIGN KEY (`id_lotto`) REFERENCES `supermercato`.`lotti` (`id_lotto`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_giacenze_scaffali` FOREIGN KEY (`id_scaffale`) REFERENCES `supermercato`.`scaffali` (`id_scaffale`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`casse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`casse` (
    `id_cassa` INT NOT NULL AUTO_INCREMENT,
    `numero_cassa` INT NOT NULL,
    `tipo` ENUM('Manuale', 'Automatica') NOT NULL,
    `stato` ENUM(
        'Attiva',
        'In manutenzione',
        'Disattivata'
    ) NULL DEFAULT 'Attiva',
    `id_edificio` INT NOT NULL,
    PRIMARY KEY (`id_cassa`),
    INDEX `fk_casse_edifici_idx` (`id_edificio` ASC) VISIBLE,
    CONSTRAINT `fk_casse_edifici` FOREIGN KEY (`id_edificio`) REFERENCES `supermercato`.`edifici` (`id_edificio`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`documenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`documenti` (
    `id_documento` INT NOT NULL AUTO_INCREMENT,
    `tipo_documento` ENUM('Scontrino', 'Fattura') NOT NULL,
    `data_documento` DATE NOT NULL,
    `ora_documento` TIME NOT NULL,
    `modalita_pagamento` ENUM(
        'Contanti',
        'Carta di Credito',
        'Carta di Debito',
        'Digital Wallet'
    ) NOT NULL,
    `importo` DECIMAL(10, 2) NOT NULL,
    `id_cassa` INT NOT NULL,
    `id_dipendente` INT NOT NULL,
    `id_cliente` INT NULL,
    PRIMARY KEY (`id_documento`),
    INDEX `fk_documenti_casse_idx` (`id_cassa` ASC) VISIBLE,
    INDEX `fk_documenti_dipendenti_idx` (`id_dipendente` ASC) VISIBLE,
    INDEX `fk_documenti_clienti_idx` (`id_cliente` ASC) VISIBLE,
    CONSTRAINT `fk_documenti_casse` FOREIGN KEY (`id_cassa`) REFERENCES `supermercato`.`casse` (`id_cassa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_documenti_dipendenti` FOREIGN KEY (`id_dipendente`) REFERENCES `supermercato`.`dipendenti` (`id_dipendente`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_documenti_clienti` FOREIGN KEY (`id_cliente`) REFERENCES `supermercato`.`clienti` (`id_cliente`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`dettagli_scontrino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`dettagli_scontrino` (
    `id_dettaglio` INT NOT NULL AUTO_INCREMENT,
    `id_documento` INT NOT NULL,
    `id_prodotto` INT NOT NULL,
    `quantita` INT NOT NULL,
    `prezzo_unitario` DECIMAL(10, 2) NOT NULL,
    `sconto_percentuale` DECIMAL(5, 2) NULL DEFAULT 0.00,
    PRIMARY KEY (`id_dettaglio`),
    INDEX `fk_dettagli_scontrino_documenti_idx` (`id_documento` ASC) VISIBLE,
    INDEX `fk_dettagli_scontrino_prodotti_idx` (`id_prodotto` ASC) VISIBLE,
    CONSTRAINT `fk_dettagli_scontrino_documenti` FOREIGN KEY (`id_documento`) REFERENCES `supermercato`.`documenti` (`id_documento`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_dettagli_scontrino_prodotti` FOREIGN KEY (`id_prodotto`) REFERENCES `supermercato`.`prodotti` (`id_prodotto`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`fornitori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`fornitori` (
    `id_fornitore` INT NOT NULL AUTO_INCREMENT,
    `nome_fornitore` VARCHAR(100) NOT NULL,
    `partita_iva` VARCHAR(20) NOT NULL,
    `email` VARCHAR(150) NULL,
    `telefono` VARCHAR(20) NULL,
    `affidabilita` TINYINT NULL,
    PRIMARY KEY (`id_fornitore`),
    UNIQUE INDEX `partita_iva_UNIQUE` (`partita_iva` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`ordini_fornitore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`ordini_fornitore` (
    `id_ordine` INT NOT NULL AUTO_INCREMENT,
    `id_fornitore` INT NOT NULL,
    `data_ordine` DATE NOT NULL,
    `data_prevista_consegna` DATE NULL,
    `stato` ENUM(
        'In attesa',
        'Consegnato',
        'Annullato'
    ) NULL DEFAULT 'In attesa',
    PRIMARY KEY (`id_ordine`),
    INDEX `fk_ordini_fornitore_fornitori_idx` (`id_fornitore` ASC) VISIBLE,
    CONSTRAINT `fk_ordini_fornitore_fornitori` FOREIGN KEY (`id_fornitore`) REFERENCES `supermercato`.`fornitori` (`id_fornitore`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`dettagli_ordine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`dettagli_ordine` (
    `id_dettaglio` INT NOT NULL AUTO_INCREMENT,
    `id_ordine` INT NOT NULL,
    `id_prodotto` INT NOT NULL,
    `quantita` INT NOT NULL,
    `prezzo_unitario` DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (`id_dettaglio`),
    INDEX `fk_dettagli_ordine_ordini_fornitore_idx` (`id_ordine` ASC) VISIBLE,
    INDEX `fk_dettagli_ordine_prodotti_idx` (`id_prodotto` ASC) VISIBLE,
    CONSTRAINT `fk_dettagli_ordine_ordini_fornitore` FOREIGN KEY (`id_ordine`) REFERENCES `supermercato`.`ordini_fornitore` (`id_ordine`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_dettagli_ordine_prodotti` FOREIGN KEY (`id_prodotto`) REFERENCES `supermercato`.`prodotti` (`id_prodotto`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`catalogo_fornitori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`catalogo_fornitori` (
    `id_fornitore` INT NOT NULL,
    `id_prodotto` INT NOT NULL,
    `prezzo_offerta` DECIMAL(10, 2) NOT NULL,
    `data_inizio` DATE NOT NULL,
    `data_fine` DATE NOT NULL,
    PRIMARY KEY (`id_fornitore`, `id_prodotto`),
    INDEX `fk_catalogo_fornitori_prodotti_idx` (`id_prodotto` ASC) VISIBLE,
    CONSTRAINT `fk_catalogo_fornitori_fornitori` FOREIGN KEY (`id_fornitore`) REFERENCES `supermercato`.`fornitori` (`id_fornitore`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_catalogo_fornitori_prodotti` FOREIGN KEY (`id_prodotto`) REFERENCES `supermercato`.`prodotti` (`id_prodotto`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`promozioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`promozioni` (
    `id_promozione` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(100) NOT NULL,
    `descrizione` TEXT NULL,
    `sconto_percentuale` DECIMAL(5, 2) NULL,
    `data_inizio` DATE NOT NULL,
    `data_fine` DATE NOT NULL,
    PRIMARY KEY (`id_promozione`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `supermercato`.`promozioni_prodotti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`promozioni_prodotti` (
    `id_promozione` INT NOT NULL,
    `id_prodotto` INT NOT NULL,
    PRIMARY KEY (
        `id_promozione`,
        `id_prodotto`
    ),
    INDEX `fk_promozioni_prodotti_prodotti_idx` (`id_prodotto` ASC) VISIBLE,
    CONSTRAINT `fk_promozioni_prodotti_promozioni` FOREIGN KEY (`id_promozione`) REFERENCES `supermercato`.`promozioni` (`id_promozione`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_promozioni_prodotti_prodotti` FOREIGN KEY (`id_prodotto`) REFERENCES `supermercato`.`prodotti` (`id_prodotto`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE = @OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_average_order_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_average_order_value` (`aov` INT);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_cannibalizzazione_promozioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_cannibalizzazione_promozioni` (
    `prodotto_promozione_1` INT,
    `prodotto_promozione_2` INT,
    `scontrini_comuni` INT,
    `qta_prodotto_1` INT,
    `qta_prodotto_2` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_carrello_medio_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_carrello_medio_cliente` (
    `id_cliente` INT,
    `nome` INT,
    `cognome` INT,
    `carrello_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_carrello_medio_tipologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_carrello_medio_tipologia` (
    `lavoro` INT,
    `carrello_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_clienti_registrati_vs_anonimi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_clienti_registrati_vs_anonimi` (
    `vendite_clienti_registrati` INT,
    `vendite_clienti_anonimi` INT,
    `totale_vendite` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_clienti_ritorno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_clienti_ritorno` (
    `clienti_ritorno` INT,
    `clienti_una_volta` INT,
    `totale_clienti` INT,
    `tasso_retention_percent` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_cross_selling_promozioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_cross_selling_promozioni` (
    `id_promozione` INT,
    `promozione` INT,
    `scontrini_con_promozione` INT,
    `scontrini_con_altri_prodotti` INT,
    `percentuale_cross_selling` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_customer_lifetime_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_customer_lifetime_value` (
    `id_cliente` INT,
    `nome` INT,
    `cognome` INT,
    `totale_speso` INT,
    `numero_acquisti` INT,
    `spesa_media_per_acquisto` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_distribuzione_peso_volume_scaffali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_distribuzione_peso_volume_scaffali` (
    `id_scaffale` INT,
    `tipo` INT,
    `peso_totale` INT,
    `volume_totale` INT,
    `utilizzo_peso_percent` INT,
    `utilizzo_volume_percent` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_efficienza_casse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_efficienza_casse` (
    `id_cassa` INT,
    `tipo_cassa` INT,
    `numero_scontrini` INT,
    `ricavi_totali` INT,
    `euro_per_ora` INT,
    `scontrini_per_ora` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_efficienza_mq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_efficienza_mq` (
    `id_edificio` INT,
    `nome_edificio` INT,
    `superficie_mq` INT,
    `ricavi_totali` INT,
    `ricavi_per_mq` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_fornitori_affidabili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_fornitori_affidabili` (
    `id_fornitore` INT,
    `nome_fornitore` INT,
    `affidabilita` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_fornitori_convenienti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_fornitori_convenienti` (
    `id_fornitore` INT,
    `nome_fornitore` INT,
    `prezzo_medio_offerta` INT,
    `prezzo_medio_vendita` INT,
    `margine_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_frequenza_vendita_prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_frequenza_vendita_prodotto` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `frequenza_vendita` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_impatto_promozioni_vendite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_impatto_promozioni_vendite` (
    `stato_promozione` INT,
    `totale_quantita` INT,
    `ricavi_totali` INT,
    `sconto_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_margine_lordo_prodotti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_margine_lordo_prodotti` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `prezzo_medio_vendita` INT,
    `prezzo_medio_acquisto` INT,
    `margine_lordo_unitario` INT,
    `vendite_totali` INT,
    `margine_totale` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_performance_edifici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_performance_edifici` (
    `id_edificio` INT,
    `nome_edificio` INT,
    `indirizzo` INT,
    `ricavi_totali` INT,
    `numero_scontrini` INT,
    `carrello_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_performance_marche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_performance_marche` (
    `id_marca` INT,
    `nome_marca` INT,
    `quantita_venduta` INT,
    `ricavi_totali` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_performance_produttori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_performance_produttori` (
    `id_produttore` INT,
    `nome_produttore` INT,
    `quantita_venduta` INT,
    `ricavi_totali` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_performance_titoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_performance_titoli` (
    `nome_titolo` INT,
    `numero_dipendenti` INT,
    `ricavi_totali` INT,
    `media_vendite_per_dipendente` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_picchi_carico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_picchi_carico` (
    `data_documento` INT,
    `ora` INT,
    `numero_scontrini` INT,
    `cassieri_attivi` INT,
    `scontrini_per_cassiere` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prezzo_vs_volumi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prezzo_vs_volumi` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `prezzo_medio_acquisto` INT,
    `quantita_venduta` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prodotti_associati`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prodotti_associati` (
    `prodotto_1` INT,
    `prodotto_2` INT,
    `frequenza` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prodotti_cari_ma_lenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prodotti_cari_ma_lenti` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `prezzo_medio_vendita` INT,
    `quantita_venduta` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prodotti_meno_venduti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prodotti_meno_venduti` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `totale_venduto` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prodotti_piu_venduti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prodotti_piu_venduti` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `totale_venduto` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_prodotti_stockout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_prodotti_stockout` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `volte_stockout` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_produttivita_ruolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_produttivita_ruolo` (
    `id_ruolo` INT,
    `nome_ruolo` INT,
    `numero_dipendenti` INT,
    `stipendio_medio` INT,
    `ricavi_totali` INT,
    `ricavi_per_dipendente` INT,
    `rapporto_stipendio_produttivita` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_promozioni_vs_vendite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_promozioni_vs_vendite` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `numero_promozioni` INT,
    `quantita_venduta` INT,
    `ricavi_generati` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_quantita_venduta_prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_quantita_venduta_prodotto` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `quantita_totale` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_redditivita_per_lavoro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_redditivita_per_lavoro` (
    `lavoro` INT,
    `ricavo_totale` INT,
    `spesa_media` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_redditivita_per_sesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_redditivita_per_sesso` (
    `sesso` INT,
    `ricavo_totale` INT,
    `spesa_media` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavi_per_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavi_per_categoria` (
    `id_categoria` INT,
    `nome_categoria` INT,
    `ricavi_totali` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavi_per_sottocategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavi_per_sottocategoria` (
    `id_sottocategoria` INT,
    `nome_sottocategoria` INT,
    `ricavi_totali` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavi_reparti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavi_reparti` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavo_per_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavo_per_categoria` (
    `id_categoria` INT,
    `nome_categoria` INT,
    `ricavo_categoria` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavo_per_prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavo_per_prodotto` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `ricavo_prodotto` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_ricavo_totale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_ricavo_totale` (`ricavo_totale` INT);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_roi_promozioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_roi_promozioni` (
    `id_promozione` INT,
    `nome` INT,
    `data_inizio` INT,
    `data_fine` INT,
    `ricavi_lordi` INT,
    `valore_sconti` INT,
    `ricavi_netto` INT,
    `roi_stimato` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_rotazione_alimentare_vs_non`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_rotazione_alimentare_vs_non` (
    `tipo_prodotto` INT,
    `vendite_totali` INT,
    `giacenza_media` INT,
    `tasso_rotazione` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_rotazione_magazzino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_rotazione_magazzino` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `vendite_totali` INT,
    `giacenza_media` INT,
    `tasso_rotazione` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_sconto_medio_prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_sconto_medio_prodotto` (
    `id_prodotto` INT,
    `nome_prodotto` INT,
    `sconto_medio` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_sconto_medio_totale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_sconto_medio_totale` (`sconto_medio_totale` INT);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_sottocategorie_low_performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_sottocategorie_low_performance` (
    `id_sottocategoria` INT,
    `nome_sottocategoria` INT,
    `numero_scontrini` INT,
    `ricavi_totali` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_spesa_per_eta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_spesa_per_eta` (
    `fascia_eta` INT,
    `ricavo_totale` INT,
    `spesa_media` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_tempo_consegna_fornitori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_tempo_consegna_fornitori` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_utilizzo_scaffali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_utilizzo_scaffali` (
    `id_scaffale` INT,
    `tipo` INT,
    `capacita_peso` INT,
    `capacita_volume` INT,
    `peso_occupato` INT,
    `volume_occupato` INT,
    `percentuale_peso` INT,
    `percentuale_volume` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_vendite_per_fascia_oraria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_vendite_per_fascia_oraria` (
    `fascia_oraria` INT,
    `numero_scontrini` INT,
    `ricavo_totale` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_vendite_per_giorno_settimana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_vendite_per_giorno_settimana` (
    `giorno_settimana` INT,
    `numero_scontrini` INT,
    `ricavo_totale` INT
);

-- -----------------------------------------------------
-- Placeholder table for view `supermercato`.`vw_vendite_per_mese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercato`.`vw_vendite_per_mese` (
    `mese` INT,
    `anno` INT,
    `ricavo_totale` INT
);